name: test project
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        run: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test